version: '3.8'

services:
  node-app:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    working_dir: /app
    command: ["yarn", "start"]

  python-app:
    build:
      context: ./python-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    working_dir: /app
    command: ["python", "app.py"]